# =============================================================================
# designing_gemma/manifest_filter.py
# Filters a doc-gen manifest.yml by path prefix, writing a scoped manifest.
#
# Used to narrow a full-repo manifest to a subset of directories before
# passing to skeleton_reader. Gemma gets relevant files only.
#
# CLI entry point: designing-gemma-filter (see pyproject.toml)
# =============================================================================

import argparse
import datetime
import sys
from pathlib import Path

import yaml


DEFAULT_SOURCE_MANIFEST = ".doc-gen/manifest.yml"
DEFAULT_OUTPUT_MANIFEST = ".doc-gen/manifest.filtered.yml"


class ManifestFilterError(Exception):
    """Raised when the source manifest cannot be read or parsed."""


# =============================================================================
# Core
# =============================================================================

def filter_manifest(
    repo_path: Path,
    include_prefixes: list[str],
    source_manifest: str = DEFAULT_SOURCE_MANIFEST,
    output_manifest: str = DEFAULT_OUTPUT_MANIFEST,
) -> dict:
    """
    Read source manifest, filter by path prefixes, write output manifest.

    An entry is included if its path starts with ANY of the specified
    prefixes (OR logic). Filtering is case-sensitive.

    Args:
        repo_path:        Root path of the target repo.
        include_prefixes: List of path prefixes to include.
                          e.g. ["python/", "bash/"]
        source_manifest:  Path to source manifest.yml relative to repo_path.
        output_manifest:  Path to write filtered manifest relative to repo_path.

    Returns:
        Dict with keys:
            total        — total entries in source manifest
            included     — entries kept after filtering
            excluded     — entries removed by filter
            output_path  — absolute path to written file

    Raises:
        ManifestFilterError: If source manifest cannot be read or parsed.
    """
    source_path = repo_path / source_manifest

    if not source_path.exists():
        raise ManifestFilterError(
            f"Source manifest not found: {source_path}\n"
            f"Run doc-gen in the target repo first."
        )

    try:
        with source_path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError as e:
        raise ManifestFilterError(
            f"Failed to parse source manifest: {e}"
        ) from e

    if not isinstance(data, dict) or "documents" not in data:
        raise ManifestFilterError(
            "Source manifest is missing 'documents' key."
        )

    documents = data["documents"]
    total     = len(documents)

    # Filter — include entry if path starts with any prefix
    included_docs = [
        doc for doc in documents
        if any(
            doc.get("path", "").startswith(prefix)
            for prefix in include_prefixes
        )
    ]

    included = len(included_docs)
    excluded = total - included

    # Build output manifest
    output = {
        "version":   1,
        "documents": included_docs,
    }

    # Write output
    out_path = repo_path / output_manifest
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("w", encoding="utf-8") as f:
        timestamp   = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        prefix_str  = ", ".join(include_prefixes)
        f.write(f"# Generated by designing-gemma manifest_filter\n")
        f.write(f"# Source: {source_manifest}\n")
        f.write(f"# Filter: {prefix_str}\n")
        f.write(f"# Generated: {timestamp}\n")
        f.write(f"# Files: {included}\n\n")
        yaml.dump(
            output,
            f,
            allow_unicode=True,
            sort_keys=False,
            default_flow_style=False,
        )

    return {
        "total":       total,
        "included":    included,
        "excluded":    excluded,
        "output_path": out_path.resolve(),
    }


# =============================================================================
# CLI entry point
# =============================================================================

def main() -> None:
    """
    CLI entry point: designing-gemma-filter <repo_path> --include <prefix> ...

    Reads .doc-gen/manifest.yml from the target repo, filters entries by
    path prefix, and writes a scoped manifest. Diagnostic tool and pre-run
    setup step for experiments that use repo_read.

    Examples:
        designing-gemma-filter /repos/dev-utils --include python/
        designing-gemma-filter /repos/dev-utils --include python/ --include bash/
        designing-gemma-filter /repos/dev-utils --include python/ \\
            --output .doc-gen/manifest.python.yml
    """
    parser = argparse.ArgumentParser(
        prog="designing-gemma-filter",
        description="Filter a doc-gen manifest.yml by path prefix",
    )
    parser.add_argument(
        "repo_path",
        help="Path to target repo (must contain .doc-gen/manifest.yml)",
    )
    parser.add_argument(
        "--include",
        action="append",
        dest="include_prefixes",
        metavar="PREFIX",
        default=[],
        required=True,
        help="Path prefix to include (repeatable, OR logic)",
    )
    parser.add_argument(
        "--source",
        dest="source_manifest",
        default=DEFAULT_SOURCE_MANIFEST,
        metavar="PATH",
        help=f"Source manifest path relative to repo root (default: {DEFAULT_SOURCE_MANIFEST})",
    )
    parser.add_argument(
        "--output",
        dest="output_manifest",
        default=DEFAULT_OUTPUT_MANIFEST,
        metavar="PATH",
        help=f"Output path relative to repo root (default: {DEFAULT_OUTPUT_MANIFEST})",
    )

    args      = parser.parse_args()
    repo_path = Path(args.repo_path).resolve()

    if not repo_path.exists():
        print(f"ERROR: repo path not found: {repo_path}")
        sys.exit(1)

    print(f"Filtering manifest for: {repo_path}")
    print(f"  Include prefixes : {args.include_prefixes}")
    print(f"  Source           : {args.source_manifest}")
    print(f"  Output           : {args.output_manifest}")

    try:
        result = filter_manifest(
            repo_path,
            include_prefixes=args.include_prefixes,
            source_manifest=args.source_manifest,
            output_manifest=args.output_manifest,
        )
    except ManifestFilterError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    print(f"\n  Total in source  : {result['total']}")
    print(f"  Included         : {result['included']}")
    print(f"  Excluded         : {result['excluded']}")
    print(f"\n  Written: {result['output_path']}")


if __name__ == "__main__":
    main()
